# SIT731 Task-7HD

#### Name : Samiha Haque
#### ID : 223935632
#### Email : s223935632@deakin.edu.au

#### Link to my .ipynb file : https://deakin365-my.sharepoint.com/:u:/g/personal/s223935632_deakin_edu_au/EWgvucrRKqpBrM1UomF03rsBOWMfEPa_ssh-1aaeiTIajQ?e=mvIgYD

In [1]:
#importing dependencies
import pandas as pd
import numpy as np

from bokeh.io import output_notebook
from bokeh.layouts import row,column
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.palettes import Spectral6
from bokeh.models import TabPanel, Tabs
from bokeh.transform import factor_cmap
output_notebook()

Loading BokehJS ...

In this task, I used 6 datasets listed below to exlore the relationships between demography of people, diabetes, oral health and smoking effects on cotinine and hydrocotinine levels. I used Bokeh to plot and visualize all the results.

#### Datasets

- [Demographic Variables and Sample Weights (P_DEMO)](https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/P_DEMO.htm)<br>
- [Diabetes (P_DIQ)](https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/P_DIQ.htm)<br>
- [Oral Health - Recommendation of Care (P_OHXREF)](https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/P_OHXREF.htm)<br>
- [Cotinine and Hydroxycotinine - Serum (P_COT)](https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/P_COT.htm)<br>
- [Smoking - Cigarette Use (P_SMQ)](https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/P_SMQ.htm)<br>
- [Smoking - Secondhand Smoke Exposure (P_SMQSHS)](https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/P_SMQSHS.htm)<br>

The demography dataset has 15560 rows and 29 columns. I reset the column names to more descriptive and user-friendly labels.

In [2]:
demography = pd.read_sas('P_DEMO.XPT', format='xport')
demography.head()

SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  RIDAGEYR  RIDAGEMN  RIDRETH1  \
0  109263.0      66.0       2.0       1.0       2.0       NaN       5.0   
1  109264.0      66.0       2.0       2.0      13.0       NaN       1.0   
2  109265.0      66.0       2.0       1.0       2.0       NaN       3.0   
3  109266.0      66.0       2.0       2.0      29.0       NaN       5.0   
4  109267.0      66.0       1.0       2.0      21.0       NaN       2.0   

   RIDRETH3  RIDEXMON  DMDBORN4  ...  FIAINTRP  MIALANG  MIAPROXY  MIAINTRP  \
0       6.0       2.0       1.0  ...       2.0      NaN       NaN       NaN   
1       1.0       2.0       1.0  ...       2.0      1.0       2.0       2.0   
2       3.0       2.0       1.0  ...       2.0      NaN       NaN       NaN   
3       6.0       2.0       2.0  ...       2.0      1.0       2.0       2.0   
4       2.0       NaN       2.0  ...       2.0      NaN       NaN       NaN   

   AIALANGA      WTINTPRP      WTMECPRP  SDMVPSU  SDMVSTRA  INDFMPIR  
0       NaN   7891.762435  8.951816e+03      3.0     156.0      4.66  
1       1.0  11689.747264  1.227116e+04      1.0     155.0      0.83  
2       NaN  16273.825939  1.665876e+04      1.0     157.0      3.06  
3       1.0   7825.646112  8.154968e+03      2.0     168.0      5.00  
4       NaN  26379.991724  5.397605e-79      1.0     156.0      5.00  

[5 rows x 29 columns]

In [3]:
demography.shape

(15560, 29)

In [4]:
demography.columns=['SEQN','Data_cycle','Interview/Exam','Gender','Age','Age(months)','Race(Hispanic)','Race','Period','Country_birth','US_duration','Education','Marital_status','Pregnancy_status','Language','Proxy','Interpreter','Language_family','Proxy_family','Interpreter_family','Language_MEC','Proxy_MEC','Interpreter_MEC','Language_ACASI','Interview_weight','MEC_weight','PSU','pseudo_stratum','Income_poverty_ratio']
demography.head()

SEQN  Data_cycle  Interview/Exam  Gender   Age  Age(months)  \
0  109263.0        66.0             2.0     1.0   2.0          NaN   
1  109264.0        66.0             2.0     2.0  13.0          NaN   
2  109265.0        66.0             2.0     1.0   2.0          NaN   
3  109266.0        66.0             2.0     2.0  29.0          NaN   
4  109267.0        66.0             1.0     2.0  21.0          NaN   

   Race(Hispanic)  Race  Period  Country_birth  ...  Interpreter_family  \
0             5.0   6.0     2.0            1.0  ...                 2.0   
1             1.0   1.0     2.0            1.0  ...                 2.0   
2             3.0   3.0     2.0            1.0  ...                 2.0   
3             5.0   6.0     2.0            2.0  ...                 2.0   
4             2.0   2.0     NaN            2.0  ...                 2.0   

   Language_MEC  Proxy_MEC  Interpreter_MEC  Language_ACASI  Interview_weight  \
0           NaN        NaN              NaN             NaN       7891.762435   
1           1.0        2.0              2.0             1.0      11689.747264   
2           NaN        NaN              NaN             NaN      16273.825939   
3           1.0        2.0              2.0             1.0       7825.646112   
4           NaN        NaN              NaN             NaN      26379.991724   

     MEC_weight  PSU  pseudo_stratum  Income_poverty_ratio  
0  8.951816e+03  3.0           156.0                  4.66  
1  1.227116e+04  1.0           155.0                  0.83  
2  1.665876e+04  1.0           157.0                  3.06  
3  8.154968e+03  2.0           168.0                  5.00  
4  5.397605e-79  1.0           156.0                  5.00  

[5 rows x 29 columns]

The diabetes dataset has 14986 rows and 28 columns. I reset the column names to more descriptive and user-friendly labels.

In [5]:
diabetes = pd.read_sas('P_DIQ.XPT', format='xport')
diabetes.head()

SEQN  DIQ010  DID040  DIQ160  DIQ180  DIQ050  DID060  DIQ060U  DIQ070  \
0  109263.0     2.0     NaN     NaN     NaN     NaN     NaN      NaN     NaN   
1  109264.0     2.0     NaN     2.0     2.0     NaN     NaN      NaN     NaN   
2  109265.0     2.0     NaN     NaN     NaN     NaN     NaN      NaN     NaN   
3  109266.0     2.0     NaN     1.0     1.0     NaN     NaN      NaN     2.0   
4  109267.0     2.0     NaN     2.0     2.0     NaN     NaN      NaN     NaN   

   DIQ230  ...  DIQ300D  DID310S  DID310D  DID320  DID330  DID341  DID350  \
0     NaN  ...      NaN      NaN      NaN     NaN     NaN     NaN     NaN   
1     NaN  ...      NaN      NaN      NaN     NaN     NaN     NaN     NaN   
2     NaN  ...      NaN      NaN      NaN     NaN     NaN     NaN     NaN   
3     NaN  ...      NaN      NaN      NaN     NaN     NaN     NaN     NaN   
4     NaN  ...      NaN      NaN      NaN     NaN     NaN     NaN     NaN   

   DIQ350U  DIQ360  DIQ080  
0      NaN     NaN     NaN  
1      NaN     NaN     NaN  
2      NaN     NaN     NaN  
3      NaN     NaN     NaN  
4      NaN     NaN     NaN  

[5 rows x 28 columns]

In [6]:
diabetes.columns=['SEQN','Diabetes','Age_diabetes','Prediabetes','Blood_test','Insulin','Insulin_duration','Duration_unit','Pills','Doctor_visit','Doctors','Doctor_duration','Check_duration','Check_unit','A1C_check','A1C','Doctor_A1C','SBP','DBP','Doctor_SBP','Doctor_DBP','LDL','Doctor_LDL','Feet','Check_feet','Unit_feet','Pupils','Retinopathy']
diabetes.head()

SEQN  Diabetes  Age_diabetes  Prediabetes  Blood_test  Insulin  \
0  109263.0       2.0           NaN          NaN         NaN      NaN   
1  109264.0       2.0           NaN          2.0         2.0      NaN   
2  109265.0       2.0           NaN          NaN         NaN      NaN   
3  109266.0       2.0           NaN          1.0         1.0      NaN   
4  109267.0       2.0           NaN          2.0         2.0      NaN   

   Insulin_duration  Duration_unit  Pills  Doctor_visit  ...  DBP  Doctor_SBP  \
0               NaN            NaN    NaN           NaN  ...  NaN         NaN   
1               NaN            NaN    NaN           NaN  ...  NaN         NaN   
2               NaN            NaN    NaN           NaN  ...  NaN         NaN   
3               NaN            NaN    2.0           NaN  ...  NaN         NaN   
4               NaN            NaN    NaN           NaN  ...  NaN         NaN   

   Doctor_DBP  LDL  Doctor_LDL  Feet  Check_feet  Unit_feet  Pupils  \
0         NaN  NaN         NaN   NaN         NaN        NaN     NaN   
1         NaN  NaN         NaN   NaN         NaN        NaN     NaN   
2         NaN  NaN         NaN   NaN         NaN        NaN     NaN   
3         NaN  NaN         NaN   NaN         NaN        NaN     NaN   
4         NaN  NaN         NaN   NaN         NaN        NaN     NaN   

   Retinopathy  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  

[5 rows x 28 columns]

In [7]:
diabetes.shape

(14986, 28)

The cotinine dataset has 13027 rows and 5 columns. I reset the column names to more descriptive and user-friendly labels.

In [8]:
cot = pd.read_sas('P_COT.XPT', format='xport')
cot.head()

SEQN   LBXCOT      LBDCOTLC  LBXHCOT      LBDHCOLC
0  109264.0    0.018  5.397605e-79    0.011  1.000000e+00
1  109266.0    0.024  5.397605e-79    0.011  1.000000e+00
2  109270.0    0.608  5.397605e-79    0.106  5.397605e-79
3  109271.0  357.000  5.397605e-79   65.700  5.397605e-79
4  109273.0  183.000  5.397605e-79   91.600  5.397605e-79

In [9]:
cot.columns=['SEQN','Cotinine','Cotinine_comment','Hydroxycotinine','Hydroxycotinine_comment']
cot.head()

SEQN  Cotinine  Cotinine_comment  Hydroxycotinine  \
0  109264.0     0.018      5.397605e-79            0.011   
1  109266.0     0.024      5.397605e-79            0.011   
2  109270.0     0.608      5.397605e-79            0.106   
3  109271.0   357.000      5.397605e-79           65.700   
4  109273.0   183.000      5.397605e-79           91.600   

   Hydroxycotinine_comment  
0             1.000000e+00  
1             1.000000e+00  
2             5.397605e-79  
3             5.397605e-79  
4             5.397605e-79

In [10]:
cot.shape

(13027, 5)

The smoking dataset has 15560 rows and 15 columns. I reset the column names to more descriptive and user-friendly labels.

In [11]:
smoke = pd.read_sas('P_SMQSHS.XPT', format='xport')
smoke.head()

SEQN  SMQ856  SMQ858  SMQ860  SMQ862  SMQ866  SMQ868  SMQ870  SMQ872  \
0  109263.0     NaN     NaN     1.0     2.0     NaN     NaN     1.0     2.0   
1  109264.0     NaN     NaN     2.0     NaN     NaN     NaN     1.0     2.0   
2  109265.0     NaN     NaN     1.0     2.0     NaN     NaN     1.0     2.0   
3  109266.0     1.0     2.0     2.0     NaN     2.0     NaN     1.0     2.0   
4  109267.0     1.0     2.0     1.0     2.0     1.0     2.0     1.0     2.0   

   SMQ874  SMQ876  SMQ878  SMQ880  SMQ940  SMAQUEX  
0     1.0     2.0     1.0     2.0     2.0      3.0  
1     1.0     2.0     1.0     2.0     2.0      1.0  
2     1.0     2.0     1.0     2.0     2.0      3.0  
3     1.0     2.0     2.0     NaN     2.0      2.0  
4     1.0     2.0     1.0     2.0     1.0      2.0

In [12]:
smoke.columns=['SEQN','Job','Job_indoors','Restaurant','Restaurant_indoors','Bar','Bar_indoors','Car','Car_indoors','Home','Home_indoors','Other','Other_indoors','E_cigs','Flag']
smoke.head()

SEQN  Job  Job_indoors  Restaurant  Restaurant_indoors  Bar  \
0  109263.0  NaN          NaN         1.0                 2.0  NaN   
1  109264.0  NaN          NaN         2.0                 NaN  NaN   
2  109265.0  NaN          NaN         1.0                 2.0  NaN   
3  109266.0  1.0          2.0         2.0                 NaN  2.0   
4  109267.0  1.0          2.0         1.0                 2.0  1.0   

   Bar_indoors  Car  Car_indoors  Home  Home_indoors  Other  Other_indoors  \
0          NaN  1.0          2.0   1.0           2.0    1.0            2.0   
1          NaN  1.0          2.0   1.0           2.0    1.0            2.0   
2          NaN  1.0          2.0   1.0           2.0    1.0            2.0   
3          NaN  1.0          2.0   1.0           2.0    2.0            NaN   
4          2.0  1.0          2.0   1.0           2.0    1.0            2.0   

   E_cigs  Flag  
0     2.0   3.0  
1     2.0   1.0  
2     2.0   3.0  
3     2.0   2.0  
4     1.0   2.0

In [13]:
smoke.shape

(15560, 15)

The cigarettes dataset has 11137 rows and 16 columns. I reset the column names to more descriptive and user-friendly labels.

In [14]:
cig = pd.read_sas('P_SMQ.XPT', format='xport')
cig.head()

SEQN  SMQ020  SMD030  SMQ040  SMQ050Q  SMQ050U  SMD057  SMQ078  SMD641  \
0  109264.0     NaN     NaN     NaN      NaN      NaN     NaN     NaN     NaN   
1  109266.0     2.0     NaN     NaN      NaN      NaN     NaN     NaN     NaN   
2  109267.0     2.0     NaN     NaN      NaN      NaN     NaN     NaN     NaN   
3  109268.0     2.0     NaN     NaN      NaN      NaN     NaN     NaN     NaN   
4  109271.0     1.0    18.0     1.0      NaN      NaN     NaN     2.0    30.0   

   SMD650  SMD100FL  SMD100MN  SMQ670  SMQ621  SMD630  SMAQUEX2  
0     NaN       NaN       NaN     NaN     1.0     NaN       2.0  
1     NaN       NaN       NaN     NaN     NaN     NaN       1.0  
2     NaN       NaN       NaN     NaN     NaN     NaN       1.0  
3     NaN       NaN       NaN     NaN     NaN     NaN       1.0  
4    20.0       NaN       NaN     1.0     NaN     NaN       1.0

In [15]:
cig.columns=['SEQN','100_cig','Age_cig','Now_cig','Quit_cig_time','Unit_time','Quit_num','Wake_cig','Monthly','Daily','Filter','Menthol','Tried_quit_cig','Number_cig','Whole_cig_age','Flag_cig']
cig.head()

SEQN  100_cig  Age_cig  Now_cig  Quit_cig_time  Unit_time  Quit_num  \
0  109264.0      NaN      NaN      NaN            NaN        NaN       NaN   
1  109266.0      2.0      NaN      NaN            NaN        NaN       NaN   
2  109267.0      2.0      NaN      NaN            NaN        NaN       NaN   
3  109268.0      2.0      NaN      NaN            NaN        NaN       NaN   
4  109271.0      1.0     18.0      1.0            NaN        NaN       NaN   

   Wake_cig  Monthly  Daily  Filter  Menthol  Tried_quit_cig  Number_cig  \
0       NaN      NaN    NaN     NaN      NaN             NaN         1.0   
1       NaN      NaN    NaN     NaN      NaN             NaN         NaN   
2       NaN      NaN    NaN     NaN      NaN             NaN         NaN   
3       NaN      NaN    NaN     NaN      NaN             NaN         NaN   
4       2.0     30.0   20.0     NaN      NaN             1.0         NaN   

   Whole_cig_age  Flag_cig  
0            NaN       2.0  
1            NaN       1.0  
2            NaN       1.0  
3            NaN       1.0  
4            NaN       1.0

In [16]:
cig.shape

(11137, 16)

The oral health dataset has 13772 rows and 12 columns. I reset the column names to more descriptive and user-friendly labels.

In [17]:
oral=pd.read_sas('P_OHXREF.XPT', format='xport')
oral.head()


SEQN  OHDEXSTS  OHDRCSTS  OHAREC  OHAROCDT  OHAROCGP  OHAROCOH  \
0  109263.0       1.0       1.0     3.0       NaN       NaN       NaN   
1  109264.0       1.0       1.0     4.0       NaN       NaN       NaN   
2  109265.0       1.0       1.0     4.0       NaN       NaN       NaN   
3  109266.0       1.0       1.0     3.0       NaN       NaN       1.0   
4  109269.0       1.0       1.0     4.0       NaN       NaN       NaN   

   OHAROCCI  OHAROCDE  OHARNF  OHAROTH  OHAPOS  
0       NaN       NaN     1.0      NaN     1.0  
1       NaN       NaN     1.0      NaN     1.0  
2       NaN       NaN     1.0      NaN     1.0  
3       NaN       NaN     NaN      NaN     1.0  
4       NaN       NaN     1.0      NaN     1.0

In [18]:
oral.columns=['SEQN','Exam_status','Care_status','Recommendation','Decayed','Gum_disease','Hygiene','Soft_tissue','Deture','No_finding','Other_findings','Recumbent']

In [19]:
oral.shape

(13772, 12)

I merged the six datasets using their common SEQN column with inner join so that only the instances which are common in all the datasets are selected. The final dataset df has 10409 rows and 100 columns.

In [20]:
df=pd.merge(demography,smoke,on='SEQN',how='inner')
df=pd.merge(df,oral,on='SEQN',how='inner')
df=pd.merge(df,cot,on='SEQN',how='inner')
df=pd.merge(df,cig,on='SEQN',how='inner')
df=pd.merge(df,diabetes,on='SEQN',how='inner')

In [21]:
df.shape

(10409, 100)

In [22]:
df.head()

SEQN  Data_cycle  Interview/Exam  Gender   Age  Age(months)  \
0  109264.0        66.0             2.0     2.0  13.0          NaN   
1  109266.0        66.0             2.0     2.0  29.0          NaN   
2  109271.0        66.0             2.0     1.0  49.0          NaN   
3  109273.0        66.0             2.0     1.0  36.0          NaN   
4  109274.0        66.0             2.0     1.0  68.0          NaN   

   Race(Hispanic)  Race  Period  Country_birth  ...   DBP  Doctor_SBP  \
0             1.0   1.0     2.0            1.0  ...   NaN         NaN   
1             5.0   6.0     2.0            2.0  ...   NaN         NaN   
2             3.0   3.0     2.0            1.0  ...   NaN         NaN   
3             3.0   3.0     2.0            1.0  ...   NaN         NaN   
4             5.0   7.0     1.0            1.0  ...  70.0       120.0   

   Doctor_DBP     LDL  Doctor_LDL  Feet  Check_feet  Unit_feet  Pupils  \
0         NaN     NaN         NaN   NaN         NaN        NaN     NaN   
1         NaN     NaN         NaN   NaN         NaN        NaN     NaN   
2         NaN     NaN         NaN   NaN         NaN        NaN     NaN   
3         NaN     NaN         NaN   NaN         NaN        NaN     NaN   
4        80.0  9999.0      6666.0   2.0         1.0        1.0     2.0   

   Retinopathy  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          2.0  

[5 rows x 100 columns]

The following columns: Data_cycle, Interview/Exam, Race(Hispanic), Period, Language, Proxy, Interpreter, Interview_weight, MEC_weight, PSU, pseudo_stratum, Flag_cig are not relevant for my analysis and can be dropped. Among these the Race is present in the dataframe again with updated values and hence Race(Hispanic) column can be discarded. 

In [23]:
print(df.columns)

Index(['SEQN', 'Data_cycle', 'Interview/Exam', 'Gender', 'Age', 'Age(months)',
       'Race(Hispanic)', 'Race', 'Period', 'Country_birth', 'US_duration',
       'Education', 'Marital_status', 'Pregnancy_status', 'Language', 'Proxy',
       'Interpreter', 'Language_family', 'Proxy_family', 'Interpreter_family',
       'Language_MEC', 'Proxy_MEC', 'Interpreter_MEC', 'Language_ACASI',
       'Interview_weight', 'MEC_weight', 'PSU', 'pseudo_stratum',
       'Income_poverty_ratio', 'Job', 'Job_indoors', 'Restaurant',
       'Restaurant_indoors', 'Bar', 'Bar_indoors', 'Car', 'Car_indoors',
       'Home', 'Home_indoors', 'Other', 'Other_indoors', 'E_cigs', 'Flag',
       'Exam_status', 'Care_status', 'Recommendation', 'Decayed',
       'Gum_disease', 'Hygiene', 'Soft_tissue', 'Deture', 'No_finding',
       'Other_findings', 'Recumbent', 'Cotinine', 'Cotinine_comment',
       'Hydroxycotinine', 'Hydroxycotinine_comment', '100_cig', 'Age_cig',
       'Now_cig', 'Quit_cig_time', 'Unit_time', 'Qu

#### Preprocessing

<b>Checking null values</b>

I checked the sum of null values in each column. Then I printed the sum and the percentage of null values in each column which are greater than 0(to find columns which have null values). It can be seen that: 

Age(months) column has all null values and can be dropped.

The columns listed here had over 60% null values which could not be imputed properly and hence can be dropped: </br>
US_duration, Pregnancy_status, Decayed, Gum_disease, Hygiene, Soft_tissue, Deture, Other_findings, Age_cig, Now_cig, Quit_cig_time, Unit_time, Quit_num, Wake_cig, Monthly, Daily, Filter, Menthol, Tried_quit_cig, Number_cig, Whole_cig_age, Age_diabetes, Insulin, Insulin_duration, Duration_unit, Pills, Doctor_visit, Doctors, Doctor_duration, Check_duration, Check_unit, A1C_check, A1C, Doctor_A1C, SBP, DBP, Doctor_SBP, Doctor_DBP, LDL, Doctor_LDL, Feet, Check_feet, Unit_feet, Pupils, Retinopathy

The columns listed here are not relevant to my anaylis since these only describe the survey procedure details and can be dropped:</br>
Language_family, Proxy_family, Interpreter_family, Language_MEC, Proxy_MEC, Interpreter_MEC, Language_ACASI

The columns listed here are not relevant to my anaylis and can be dropped:</br>
No_finding, Recumbent, Blood_test, Prediabetes

In [24]:
for i in df.columns:
    if df[i].isnull().sum()>0:
        print(f"{i} -> {df[i].isnull().sum()} -> {round(df[i].isnull().sum()/df.shape[0],2)*100}%")

Age(months) -> 10409 -> 100.0%
US_duration -> 7730 -> 74.0%
Education -> 1865 -> 18.0%
Marital_status -> 1865 -> 18.0%
Pregnancy_status -> 8659 -> 83.0%
Language_family -> 640 -> 6.0%
Proxy_family -> 640 -> 6.0%
Interpreter_family -> 640 -> 6.0%
Language_MEC -> 620 -> 6.0%
Proxy_MEC -> 620 -> 6.0%
Interpreter_MEC -> 620 -> 6.0%
Language_ACASI -> 2185 -> 21.0%
Income_poverty_ratio -> 1407 -> 14.000000000000002%
Job -> 1444 -> 14.000000000000002%
Job_indoors -> 5666 -> 54.0%
Restaurant -> 54 -> 1.0%
Restaurant_indoors -> 4817 -> 46.0%
Bar -> 1444 -> 14.000000000000002%
Bar_indoors -> 9259 -> 89.0%
Car -> 54 -> 1.0%
Car_indoors -> 629 -> 6.0%
Home -> 54 -> 1.0%
Home_indoors -> 5755 -> 55.00000000000001%
Other -> 54 -> 1.0%
Other_indoors -> 3976 -> 38.0%
E_cigs -> 252 -> 2.0%
Recommendation -> 434 -> 4.0%
Decayed -> 7581 -> 73.0%
Gum_disease -> 9327 -> 90.0%
Hygiene -> 7719 -> 74.0%
Soft_tissue -> 10322 -> 99.0%
Deture -> 9848 -> 95.0%
No_finding -> 4736 -> 45.0%
Other_findings -> 10319 ->

<b>Dropping columns</b>

After dropping the unnecessary columns and columns with null values, the dataset has 10409 rows and 31 columns

In [25]:
df.drop(columns=['Age(months)','Data_cycle', 'Interview/Exam','Race(Hispanic)','Period','Pregnancy_status', 'Language','Proxy', 'Interpreter','Language_family',
                 'Proxy_family', 'Interpreter_family','Language_MEC','Proxy_MEC', 'Interpreter_MEC', 'Language_ACASI', 'Interview_weight',
                 'MEC_weight', 'PSU', 'pseudo_stratum','US_duration','Age_cig', 'Now_cig', 'Quit_cig_time', 'Unit_time','Quit_num', 'Wake_cig',
                 'Monthly', 'Daily', 'Filter', 'Menthol','Tried_quit_cig', 'Number_cig', 'Whole_cig_age', 'Flag_cig','Decayed', 'Gum_disease', 
                 'Hygiene', 'Soft_tissue', 'Deture','No_finding', 'Other_findings', 'Recumbent','Age_diabetes','Insulin','Insulin_duration',
                 'Duration_unit','Pills','Doctor_visit','Doctors','Doctor_duration','Check_duration','Check_unit','A1C_check','A1C','Doctor_A1C',
                 'SBP','DBP','Doctor_SBP','Doctor_DBP','LDL','Doctor_LDL','Feet','Check_feet','Unit_feet','Pupils','Retinopathy','Blood_test','Prediabetes'],inplace=True)

In [26]:
df.shape

(10409, 31)

In [27]:
for i in df.columns:
    if df[i].isnull().sum()>0:
        print(f"{i} -> {df[i].isnull().sum()} -> {round(df[i].isnull().sum()/df.shape[0],2)*100}%")

Education -> 1865 -> 18.0%
Marital_status -> 1865 -> 18.0%
Income_poverty_ratio -> 1407 -> 14.000000000000002%
Job -> 1444 -> 14.000000000000002%
Job_indoors -> 5666 -> 54.0%
Restaurant -> 54 -> 1.0%
Restaurant_indoors -> 4817 -> 46.0%
Bar -> 1444 -> 14.000000000000002%
Bar_indoors -> 9259 -> 89.0%
Car -> 54 -> 1.0%
Car_indoors -> 629 -> 6.0%
Home -> 54 -> 1.0%
Home_indoors -> 5755 -> 55.00000000000001%
Other -> 54 -> 1.0%
Other_indoors -> 3976 -> 38.0%
E_cigs -> 252 -> 2.0%
Recommendation -> 434 -> 4.0%
Cotinine -> 841 -> 8.0%
Cotinine_comment -> 841 -> 8.0%
Hydroxycotinine -> 841 -> 8.0%
Hydroxycotinine_comment -> 841 -> 8.0%
100_cig -> 1444 -> 14.000000000000002%


The dataset is grouped by 'Age' and then the 'Education' column is viewed. I checked the not null(~) instances of the 'Education' column and found the average of them for each age group. It can be seen that for ages 12 to 19, the means are all nan which means the Education level is not defined for them. Therefore, I categorized two groups, one group is ages 12 and 13 and another group is ages 13 and above. For the first group I put 1 (Less than 9th grade according to the dataset metadata) and for the second group I put 2 (9-11th grade according to the metadata).

<b>Handling Education column</b>

In [28]:
x=df.groupby('Age')[['Education']]
for age, group_data in x:
    print(age)
    print(group_data[~group_data['Education'].isna()]['Education'].mean())
    print("-------------------------------------")

12.0
nan
-------------------------------------
13.0
nan
-------------------------------------
14.0
nan
-------------------------------------
15.0
nan
-------------------------------------
16.0
nan
-------------------------------------
17.0
nan
-------------------------------------
18.0
nan
-------------------------------------
19.0
nan
-------------------------------------
20.0
3.260869565217391
-------------------------------------
21.0
3.4310344827586206
-------------------------------------
22.0
3.5693430656934306
-------------------------------------
23.0
3.8296296296296295
-------------------------------------
24.0
3.5271317829457365
-------------------------------------
25.0
3.7244094488188977
-------------------------------------
26.0
3.752136752136752
-------------------------------------
27.0
3.6371681415929205
-------------------------------------
28.0
3.955223880597015
-------------------------------------
29.0
3.693877551020408
-------------------------------------
30.0
3.8

In [29]:
df.loc[df['Age'] <= 13, 'Education'] = 1
df.loc[(df['Age'] > 13) & (df['Age'] <= 19), 'Education'] = 2

In [30]:
x=df.groupby('Age')[['Education']]
for age, group_data in x:
    print(age)
    print(group_data[~group_data['Education'].isna()]['Education'].mean())
    print("-------------------------------------")

12.0
1.0
-------------------------------------
13.0
1.0
-------------------------------------
14.0
2.0
-------------------------------------
15.0
2.0
-------------------------------------
16.0
2.0
-------------------------------------
17.0
2.0
-------------------------------------
18.0
2.0
-------------------------------------
19.0
2.0
-------------------------------------
20.0
3.260869565217391
-------------------------------------
21.0
3.4310344827586206
-------------------------------------
22.0
3.5693430656934306
-------------------------------------
23.0
3.8296296296296295
-------------------------------------
24.0
3.5271317829457365
-------------------------------------
25.0
3.7244094488188977
-------------------------------------
26.0
3.752136752136752
-------------------------------------
27.0
3.6371681415929205
-------------------------------------
28.0
3.955223880597015
-------------------------------------
29.0
3.693877551020408
-------------------------------------
30.0
3.8

<b>Handling Marriage_status column</b>

I filtered the dataset by the null instances of the 'Marital_status' column and selected the 'Age' column's max value. It can be seen that people with at max 19 years of age did not provide their Marital Status and hence I assumed that they are not married. It can also be seen that none of the participants 19 and under inputted their Marital status. Hence I imputed the value 3 (Never married according to the metadata) for all people 19 and under.

In [31]:
df[df['Marital_status'].isna()]['Age'].max()

19.0

In [32]:
df[df['Age']<=19]['Marital_status'].mean()

nan

In [33]:
df.loc[df['Age'] <= 19, 'Marital_status'] = 3

<b>Handling Job, Job_indoors, Restaurant_indoors, Bar, Bar_indoors, Car_indoors, Home_indoors, Other_indoors columns</b>

Job =  Last 7-d worked at job not at home? - metadata

I filtered the dataset by the null instances of the 'Job' column and selected the 'Age' column's max value. It can be seen that people with at max 17 years of age did not provide their Job status and hence I assumed that they are not employed due to their age. It can also be seen that none of the participants 17 and under inputted their Job status. Hence I imputed the value 2 (No according to the metadata) for all people 17 and under which means they did not work at job for last 7 days.

In [34]:
df[df['Job'].isna()]['Age'].max()

17.0

In [35]:
df[df['Age']<=17]['Job'].mean()

nan

In [36]:
df.loc[df['Age']<=17, 'Job']=2

Job_indoors=Last 7-d at job someone smoked indoors? - metadata

I filtered the dataset using null instances of the 'Job_indoors' column and then checked the number of values in 'Job' column. It can be seen that people who did not respond to 'Job_indoors' were not at their job for the last 7 days(not at job=2 according to metadata). Therefore, I imputed the null values where 'Job'=2 in 'Job_indoors' column with 2(no according to metadata) which means since they were not at their job for last 7 days, they did not find someone smoking indoors at their job either.

In [37]:
df[df['Job_indoors'].isna()]['Job'].value_counts()

Job
2.0    5665
9.0       1
Name: count, dtype: int64

In [38]:
df.loc[df['Job']==2,'Job_indoors']=2

Restaurant_indoors=Last 7-d at rest someone smoked indoors? - metadata

I filtered the dataset using null instances of the 'Restaurant_indoors' column and then checked the number of values in 'Restaurant' column. It can be seen that people who did not respond to 'Restaurant_indoors' were not at a restaurant for the last 7 days(not at restaurant=2 according to metadata). Therefore, I imputed the null values where 'Restaurant'=2 in 'Restaurant_indoors' column with 2(no according to metadata) which means since they were not at any restaurant for last 7 days, they did not find someone smoking indoors at the restaurant either.


In [39]:
df[df['Restaurant_indoors'].isna()]['Restaurant'].value_counts()

Restaurant
2.0    4758
9.0       5
Name: count, dtype: int64

In [40]:
df.loc[df['Restaurant']==2,'Restaurant_indoors']=2

Bar=Last 7-d spent time in a bar? - metadata

I filtered the dataset by the null instances of the 'Bar' column and selected the 'Age' column's max value. It can be seen that people with at max 17 years of age did not provide their response to being at a bar since they are prohibited from bars due to their age. It can also be seen that none of the participants 17 and under inputted their Bar information. Hence I imputed the value 2 (No according to the metadata) for all people 17 and under which means they did not go to a bar for last 7 days.

Bar_indoors=Last 7-d in bar someone smoked indoors?

I filtered the dataset using null instances of the 'Bar_indoors' column and then checked the number of values in 'Bar' column. It can be seen that people who did not respond to 'Bar_indoors' were not at a bar for the last 7 days(not at bar=2 according to metadata). Therefore, I imputed the null values where 'Bar'=2 in 'Bar_indoors' column with 2(no according to metadata) which means since they were not at any bar for last 7 days, they did not find someone smoking indoors at the bar either.

In [41]:
df[df['Bar'].isna()]['Age'].max()

17.0

In [42]:
df[df['Age']<=17]['Bar'].mean()

nan

In [43]:
df.loc[df['Age']<=17,'Bar']=2

In [44]:
df[df['Bar_indoors'].isna()]['Bar'].value_counts()

Bar
2.0    9259
Name: count, dtype: int64

In [45]:
df.loc[df['Bar']==2,'Bar_indoors']=2

Car_indoors=Last 7-d someone smoked in car? - metadata


I filtered the dataset using null instances of the 'Car_indoors' column and then checked the number of values in 'Car' column. It can be seen that people who did not respond to 'Car_indoors' were not in a car for the last 7 days(not at bar=2 according to metadata). Therefore, I imputed the null values where 'Car'=2 in 'Car_indoors' column with 2(no according to metadata) which means since they were not in any car for last 7 days, they did not find someone smoking indoors in the car either.

In [46]:
df[df['Car_indoors'].isna()]['Car'].value_counts()

Car
2.0    575
Name: count, dtype: int64

In [47]:
df.loc[df['Car']==2,'Car_indoors']=2

Home_indoors= Last 7-d in home someone smoked indoors? - metadata

I filtered the dataset using null instances of the 'Home_indoors' column and then checked the number of values in 'Home' column. It can be seen that people who did not respond to 'Home_indoors' were not at home for the last 7 days(not at home=2 according to metadata). Therefore, I imputed the null values where 'Home'=2 in 'Home_indoors' column with 2(no according to metadata) which means since they were not at home for last 7 days, they did not find someone smoking indoors at home either.

In [48]:
df[df['Home_indoors'].isna()]['Home'].value_counts()

Home
2.0    5699
9.0       2
Name: count, dtype: int64

In [49]:
df.loc[df['Home']==2,'Home_indoors']=2

Other_indoors= Last 7-d in other indoor someone smoked? - metadata

I filtered the dataset using null instances of the 'Other_indoors' column and then checked the number of values in 'Other' column. It can be seen that people who did not respond to 'Other_indoors' were not at a Other places for the last 7 days(not at other=2 according to metadata). Therefore, I imputed the null values where 'Other'=2 in 'Other_indoors' column with 2(no according to metadata) which means since they were not at any other place for last 7 days, they did not find someone smoking indoors at the other places either.

In [50]:
df[df['Other_indoors'].isna()]['Other'].value_counts()

Other
2.0    3918
9.0       4
Name: count, dtype: int64

In [51]:
df.loc[df['Other']==2,'Other_indoors']=2

In [52]:
for i in df.columns:
    if df[i].isnull().sum()>0:
        print(f"{i} -> {df[i].isnull().sum()} -> {round(df[i].isnull().sum()/df.shape[0],2)*100}%")

Income_poverty_ratio -> 1407 -> 14.000000000000002%
Job_indoors -> 1 -> 0.0%
Restaurant -> 54 -> 1.0%
Restaurant_indoors -> 59 -> 1.0%
Car -> 54 -> 1.0%
Car_indoors -> 54 -> 1.0%
Home -> 54 -> 1.0%
Home_indoors -> 56 -> 1.0%
Other -> 54 -> 1.0%
Other_indoors -> 58 -> 1.0%
E_cigs -> 252 -> 2.0%
Recommendation -> 434 -> 4.0%
Cotinine -> 841 -> 8.0%
Cotinine_comment -> 841 -> 8.0%
Hydroxycotinine -> 841 -> 8.0%
Hydroxycotinine_comment -> 841 -> 8.0%
100_cig -> 1444 -> 14.000000000000002%


The rows which have null values can be dropped now since the percentage of null values in each column are low. After handling all null values, the dataset has 6913 rows and 31 columns.

In [53]:
df.dropna(inplace=True)

In [54]:
df.shape

(6913, 31)

<b>Handling binary values in Cotinine_comments and Hydroxycotinine_comments</b>

Any comment columns such as Cotinine_comment and Hydroxycotinine_comment must have binary 0 and 1 values according to metadata. Thefore, I checked their values and then replaced the extremely small value with 0 and extremely close 1 with 1. I used filterning technique to complete it.

In [55]:
print('Cotinine_comments:',df['Cotinine_comment'].value_counts())
print()
print('Hydroxycotinine_comment:',df['Hydroxycotinine_comment'].value_counts())
print()

Cotinine_comments: Cotinine_comment
5.397605e-79    4611
1.000000e+00    2302
Name: count, dtype: int64

Hydroxycotinine_comment: Hydroxycotinine_comment
1.000000e+00    3555
5.397605e-79    3358
Name: count, dtype: int64



In [56]:
df.loc[df['Cotinine_comment']<1,'Cotinine_comment']=0
df.loc[df['Cotinine_comment']>=1,'Cotinine_comment']=1

df.loc[df['Hydroxycotinine_comment']<1,'Hydroxycotinine_comment']=0
df.loc[df['Hydroxycotinine_comment']>=1,'Hydroxycotinine_comment']=1


In [57]:
print('Cotinine_comments:',df['Cotinine_comment'].value_counts())
print()
print('Hydroxycotinine_comment:',df['Hydroxycotinine_comment'].value_counts())
print()


Cotinine_comments: Cotinine_comment
0.0    4611
1.0    2302
Name: count, dtype: int64

Hydroxycotinine_comment: Hydroxycotinine_comment
1.0    3555
0.0    3358
Name: count, dtype: int64



<b>Handling a single anomalous value in 100_cig column</b>

100_cig=Smoked at least 100 cigarettes in life - metadata

I found out the index where '100_cig' column had the value 7(refused to tell - according to metadata). Since this instance does not provide any information, I dropped this single row.

In [58]:
df.where(df['100_cig']==7).dropna().index

Index([110], dtype='int64')

In [59]:
df=df.drop(110,axis=0).reset_index(drop=True)

In [60]:
df.columns

Index(['SEQN', 'Gender', 'Age', 'Race', 'Country_birth', 'Education',
       'Marital_status', 'Income_poverty_ratio', 'Job', 'Job_indoors',
       'Restaurant', 'Restaurant_indoors', 'Bar', 'Bar_indoors', 'Car',
       'Car_indoors', 'Home', 'Home_indoors', 'Other', 'Other_indoors',
       'E_cigs', 'Flag', 'Exam_status', 'Care_status', 'Recommendation',
       'Cotinine', 'Cotinine_comment', 'Hydroxycotinine',
       'Hydroxycotinine_comment', '100_cig', 'Diabetes'],
      dtype='object')

<b>Creating new dataframe with categorical values for ease of plotting</b>

I copied the dataset in x variable. Then I changed the numeric categories to categorical so that it is descriptive and easier to read from plots during analysis.

According to the metadata</br>
For races: 1.0 is Mexican American, 2.0 is Other Hispanic, 3.0 is Non-Hispanic White, 4.0 is Non-Hispanic Black, 6.0 is Non-Hispanic Asian and 7.0 is Other Race - Including Multi-Racial

For gender: 1.0 is Male and 2.0 is Female

For oral recommendation(when to see a dentist): 1 means Immediate care, 2 means Within 2 weeks, 3 means Soon and 4 mean No need

For diabetes: 1 means Yes, 2 means No, 3 means Borderline and 9 means Not Known

For country of birth: 1 means USA(Born in 50 US states or Washington, DC), 2 means Others and 77 means Refused

For if they smoked at least 100 cigarettes in life: 1 means Yes and 2 means No

In [61]:
x=df.copy()

race_labels={1.0:"Mexican American",2.0:"Other Hispanic",3.0:"Non-Hispanic White",4.0:"Non-Hispanic Black",6.0:"Non-Hispanic Asian",7.0:"Other Race - Including Multi-Racial"}

races=['Non-Hispanic White', 'Non-Hispanic Asian', 'Mexican American',
       'Non-Hispanic Black', 'Other Hispanic',
       'Other Race - Including Multi-Racial']

gender_labels={1.0:"Male",2.0:"Female"}

rec_labels={1:'Immediate care',2:'Within 2 weeks',3:'Soon',4:'No need'}
rec = ['Immediate care', 'Within 2 weeks', 'Soon', 'No need']

diab_labels={1:"Yes",2:"No",3:"Borderline",9:"Not Known"}
diab=['Yes','No','Borderline','Not Known']

country={1:'USA',2:'Others',77:'Refused'}

cig={1:"Yes",2:"No"}

x['Diabetes'].replace(diab_labels,inplace=True)
x['Gender'].replace(gender_labels,inplace=True)
x['Race'].replace(race_labels,inplace=True)
x['Recommendation'].replace(rec_labels,inplace=True)
x['Country_birth'].replace(country,inplace=True)
x['100_cig'].replace(cig,inplace=True)

#### Analysis on Demography and Diabetes relations

<b>Exploring diabetes and gender relationships and diabetes and race relationships</b>

I grouped the dataset using 'Diabetes' column followed by 'Gender' column so that the instances under each 'Diabetes' group will be further grouped by 'Gender' and used group_gender to store the grouped dataset. Then I applied the size() function to aggregate the grouped data and find the number of instances under each 'Diabetes', 'Gender' group in order to count the number of times any unique combination of 'Diabetes' and 'Gender'.

Next, I grouped the dataset using 'Diabetes' column followed by 'Race' column so that the instances under each 'Diabetes' group will be further grouped by 'Race' and used group_race1 to store the dataset. Then I applied the size() function to aggregate the grouped data and find the number of instances under each 'Diabetes', 'Race' group in order to count the number of times any unique combination of 'Diabetes' and 'Race'.


In [62]:
group_gender = x.groupby(['Diabetes','Gender'])
group_gender=group_gender.size().reset_index(name='count')
group_gender=group_gender.groupby(['Diabetes','Gender'])


group_race=x.groupby(['Diabetes','Race'])
group_race= group_race.size().reset_index(name='count')
group_race=group_race.groupby(['Diabetes','Race'])


I used bokeh's bar plot to plot the grouped datasets group_gender and group_race datasets in two different interractive tabs which can be switched on click. I used tooltips which allow to display the count(frequency) and diabetes and gender/race of a bar on hovering. I also used different colors for different groups for ease of visualisation.

In [63]:
TOOLTIPS1 = [
    ("Frequency", "@count_mean"),
    ("Diabetes, Gender", "@Diabetes_Gender")]

TOOLTIPS2 = [
    ("Frequency", "@count_mean"),
    ("Diabetes, Race", "@Diabetes_Race")]
    

index_cmap1 = factor_cmap('Diabetes_Gender', palette=Spectral6, factors=sorted(x['Diabetes'].unique()), end=1)
index_cmap2 = factor_cmap('Diabetes_Race', palette=Spectral6, factors=sorted(x['Diabetes'].unique()), end=1)

p1 = figure(title="Frequency by Diabetes and Gender count", height=500, width=800, x_range=group_gender, tooltips=TOOLTIPS1,background_fill_color="#FEFEF8")
p1.vbar(x='Diabetes_Gender', top='count_mean', width=1, source=group_gender, line_color="white",fill_color=index_cmap1)
p1.x_range.range_padding = 0.05
p1.xaxis.axis_label = "Gender count grouped by Diabetes"
p1.yaxis.axis_label = "Frequency"
p1.xaxis.major_label_orientation = 1.2


p2 = figure(title="Frequency by Diabetes and Race count", height=500, width=800, x_range=group_race, tooltips=TOOLTIPS2,background_fill_color="#FEFEF8")
p2.vbar(x='Diabetes_Race', top='count_mean', width=1, source=group_race, line_color="white",fill_color=index_cmap2)
p2.x_range.range_padding = 0.05
p2.xaxis.axis_label = "Race count grouped by Diabetes"
p2.yaxis.axis_label = "Frequency"
p2.xaxis.major_label_orientation = 1.2

tab1 = TabPanel(child=p1, title="Gender count") 
tab2 = TabPanel(child=p2, title="Race count") 
tabs = Tabs(tabs=[tab1, tab2])
show(tabs)

# show(row(p1,p2))


<b>Findings:</b> </br>
Gender count tab:
- More number of people do not have diabetes(3019 females and 2682 males in total)
- Among those who have diabetes, the number of males(564) is higher than females(450) -  approximately 12%
- There is a small group of people who are on the boderline of diabetes and even there the number of males(107) is higher than females(89) - approximately 10% more
- There is one anomalous result of a female whose diabetes status is not known

Race count tab:
- Again, number of people who do not have diabetes is much higher.
- Among those who have diabetes, Non-Hispanic White people have the highest count(359), followed by Non-Hispanic Black people(273). Whereas, Other Race-Including Multi Racial group has the lowest count in terms of diabetes. The other races such as Mexican American(126), Non-Hispanic Asian(106) and Other Hispanic(97) have close counts.
- There is also a very small subsection of people who have borderline diabetes, and among them Non-Hispanic Black(59) and Non-Hispanic White(53) races have highest numbers.
- There is likely a few anomalous result of Other Hispanic race whose diabetes status is not known.

<b>Exploring diabetes and age relationships</b>

I used bokeh's circle plot to display the 'Age' range under different 'Diabetes' status. I used tooltips which allow to display the age ) and gender of each point on hovering. I also used alpha=0.1(least opacity) so that overlapping datapoints can be seen to identify compact cluster groups.

In [64]:
TOOLTIPS4 = [
    ("Gender", "@Gender"),
    ("Age", "@Age")]
p3 = figure(title='Age Distribution by Diabetes Status',height=450,width=800,x_range=x['Diabetes'].unique(),tooltips=TOOLTIPS4,background_fill_color="#FEFEF8")
p3.circle(x='Diabetes', y='Age', source=x,alpha=0.1,size=15,color='#8BD688')
p3.xaxis.axis_label = "Diabetes"
p3.yaxis.axis_label = "Age"
show(p3)

<b>Findings:</b> </br>
- The number of people who do not have diabetes range from 18 years to 80 years and all age groups are equally packed.
- there is one anomalous result of a female whose diabetes status is not known 

Among those who have diabetes:
- the least age is 18 but it is just 2 Males.
- the minimum age for Females is 22.
- The density of the circles is sparse from ages 18 to 35.
- From ages 35 onwards till 80 the density seems compact which means more people in that age range typically have diabetes
  
Among those who have borderline diabetes:
- the least age is 19 and it 2 Females
- the maximum age is 80
- the density is mostly sparse throughout but there are dense clusters around ages 44 to 46, 58 to 66 and 79 to 80 which suggests more people within these age ranges are likely to be borderline diabetic.

#### Analysis on Demography, Diabetes and Oral Health relations

<b>Exploring diabetes and oral recommendation relationships</b>

I grouped the dataset using 'Diabetes' column followed by 'Recommendation' column so that the instances under each 'Diabetes' group will be further grouped by 'Recommendation' and used group_rec to store the grouped dataset(here Recommendation means oral care recommendation). Then I applied the size() function to aggregate the grouped data and find the number of instances under each 'Diabetes', 'Recommendation' group in order to count the number of times any unique combination of 'Diabetes' and 'Recommendation'. Next I created a dictionary called data which which has the following keys : 'Diabetes', 'Immediate care', 'Within 2 weeks', 'Soon' and 'No need'. The 'Diabetes' key's values are the status of diabetes. The recommendation keys' values are a list of length 4 which will indicate to any of the 4 statuses of diabetes. The values in each index will be the count/frequency of people who need that recommendation key's care and have the corresponding diabetes status.The data dictionary is printed below for reference.


In [65]:
group_rec=x.groupby(['Diabetes','Recommendation']).size().reset_index(name='count')

In [66]:
data={'Diabetes':diab} #diab was listed before as ['Yes','No','Borderline','Not Known'] i.e. status of diabetes

for i in rec: #rec was listed before as ['Immediate care', 'Within 2 weeks', 'Soon', 'No need'] i.e. types of oral recommendation
    ind=group_rec.where(group_rec['Recommendation']==i).dropna().index.to_list()
    lst=np.zeros(len(diab))
    for j in ind:
        d=group_rec.iloc[j,0]
        c=group_rec.iloc[j,2]
        for z in range(len(diab)):
            if diab[z]==d:
                lst[z]=c

    data[i]=lst.tolist()

In [67]:
data

{'Diabetes': ['Yes', 'No', 'Borderline', 'Not Known'],
 'Immediate care': [2.0, 4.0, 0.0, 0.0],
 'Within 2 weeks': [67.0, 285.0, 15.0, 0.0],
 'Soon': [450.0, 2236.0, 63.0, 0.0],
 'No need': [495.0, 3176.0, 118.0, 1.0]}

I used bokeh's stacked bar plot to plot the data dictionary. I used tooltips which allow to display the count(frequency) and diabetes status on hovering. I also used different colors for different stacks for ease of visualisation.

In [68]:
    p4 = figure(title='Diabetes Types by Oral Recommendation',height=500,width=800,x_range=diab,tools="hover", tooltips="$name @Diabetes: @$name",background_fill_color="#FEFEF8")

p4.vbar_stack(stackers=rec, x='Diabetes', width=0.5, color=[Spectral6[0],Spectral6[1],Spectral6[3],Spectral6[4]], source=data,
              legend_label=rec)

p4.xaxis.axis_label = "Diabetes"
p4.yaxis.axis_label = "Frequency by Oral Recommendation"
show(p4)

<b>Findings:</b> </br>
- Again, the number of people who do not have diabetes is much higher and among them there are 3176 people who don't need any oral care, 2236 people who need oral care soon and 285 people need oral care within 2 weeks. Therefore, majority of people who do not have diabetes have overall good oral report.
- Among those who have diabetes, 495 people do not need oral care but 450 people need oral care soon and 67 people need oral care within 2 weeks. This suggests that majority of people (450+67=517) who have diabetes need oral care.
- Among those who have borderline diabetes, 118 people do not need oral care whereas 63 people need oral care soon. This indicates that this majority shifts to more people needing oral care when diabetes is detected.
- There is likely a few anomalous  whose diabetes status is not known.

#### Analysis on Demography, Cotinine/Hydroxycotinine and Smoking relations

<b>Comparing the cotinine and hydroxycotinine levels of smokers and non-smokers</b>

According to metadat, Cotinine and Hydroxycotinine levels indicate active smoking and 0.015 is the threshold value, i.e. any person with levels over 0.015  is considered to have used tobacco.

I created a function called map_smoking which takes the row of the dataframe and then check the Cotinine and Hydroxycotinine levels, if both the values are less than 0.015(threshold), then 'Non smoker' is returned. Then I used only Cotinine levels(the main metabolite of nicotine, is typically considered the most reliable marker for nicotine exposure.) to further divide into 'Light smoker', 'Moderate smoker', 'Heavy smoker' and 'Extreme level smoker'. Finally, I used apply function of the dataframe to create a new column 'Smoking level' to map the smoking levels to individual persons.

In [69]:
def map_smoking(row):
    cotinine_level=row['Cotinine']
    hydroxycotinine_level=row['Hydroxycotinine']
    if cotinine_level<0.015 and hydroxycotinine_level<0.015:
        return 'Non smoker'
    elif cotinine_level<=1:
        return 'Light smoker'
    elif cotinine_level<=10:
        return 'Moderate smoker'
    elif cotinine_level<=100:
        return 'Heavy smoker'
    elif cotinine_level>100:
        return 'Extreme level smoker'

x['Smoking_level'] = x.apply(map_smoking,axis=1)
x.head()

SEQN  Gender   Age                                 Race Country_birth  \
0  109266.0  Female  29.0                   Non-Hispanic Asian        Others   
1  109273.0    Male  36.0                   Non-Hispanic White           USA   
2  109274.0    Male  68.0  Other Race - Including Multi-Racial           USA   
3  109282.0    Male  76.0                   Non-Hispanic White           USA   
4  109290.0  Female  68.0                   Non-Hispanic Black           USA   

   Education  Marital_status  Income_poverty_ratio  Job  Job_indoors  ...  \
0        5.0             3.0                  5.00  1.0          2.0  ...   
1        4.0             3.0                  0.83  1.0          2.0  ...   
2        4.0             3.0                  1.20  2.0          2.0  ...   
3        5.0             1.0                  3.61  2.0          2.0  ...   
4        5.0             2.0                  5.00  1.0          2.0  ...   

   Exam_status  Care_status  Recommendation  Cotinine  Cotinine_comment  \
0          1.0          1.0            Soon     0.024               0.0   
1          1.0          1.0         No need   183.000               0.0   
2          1.0          1.0            Soon     0.019               0.0   
3          1.0          1.0         No need     0.051               0.0   
4          1.0          1.0         No need     0.011               1.0   

   Hydroxycotinine  Hydroxycotinine_comment  100_cig  Diabetes  \
0            0.011                      1.0       No        No   
1           91.600                      0.0      Yes        No   
2            0.022                      0.0       No       Yes   
3            0.021                      0.0      Yes        No   
4            0.011                      1.0       No       Yes   

          Smoking_level  
0          Light smoker  
1  Extreme level smoker  
2          Light smoker  
3          Light smoker  
4            Non smoker  

[5 rows x 32 columns]

I filtered the dataset using 'Smoking_level' and selected only rows which had 'Smoking_level' as 'Non smoker' and stored the subset in non_smokers variable. Next I again filtered the dataset to selected all the rows where 'Smoking_level' is not 'Non smoker' using ~ and stored the subset in smokers variable.

In [70]:
non_smokers=x.loc[x['Smoking_level']=='Non smoker'].reset_index(drop=True)
smokers=x.loc[~(x['Smoking_level']=='Non smoker')].reset_index(drop=True)
smokers.rename_axis('index',inplace=True)


I grouped the smokers dataset using 'Race' column and selected the 'Cotinine' column and aggregated it using mean and stored the resulting dataframe in group_smokers_cot. Similarly, I grouped the smokers dataset using 'Race' column and selected the 'Hydroxicotinine' column and aggregated it using mean and stored the dataframe in group_smokers_hydro. I carried out the same method on non_smokers dataset and created two dataframes group_non_smokers_cot and group_non_smokers_hydro. For all the four datasets, I renamed the index which stores the mean levels to 'Avg'.

In [71]:
group_smokers_cot=smokers.groupby(['Race'])['Cotinine'].mean().reset_index(name='Avg')
group_smokers_hydro=smokers.groupby(['Race'])['Hydroxycotinine'].mean().reset_index(name='Avg')
group_non_smokers_cot=non_smokers.groupby(['Race'])['Cotinine'].mean().reset_index(name='Avg')
group_non_smokers_hydro=non_smokers.groupby(['Race'])['Hydroxycotinine'].mean().reset_index(name='Avg')

I used bokeh's bar plot to plot the grouped datasets group_gender and group_race datasets in two different interractive tabs which can be switched on click. I used tooltips which allow to display the count(frequency) and diabetes and gender/race of a bar on hovering. I also used different colors for different groups for ease of visualisation.

I used bokeh's bar plot to plot the grouped datasets group_smokers_cot and group_smokers_hydro on top of one another using alpha=0.4 to reduce the opacity to vosualize the smokers' Cotinine and Hydroxycotinine levels. I did the same to plot the grouped datasets group_non_smokers_cot and group_non_smokers_hydro on top of one another using alpha=0.4 to reduce the opacity to vosualize the non-smokers' Cotinine and Hydroxycotinine levels. I used tooltips which allow to display the average levels of Cotinie and Hydroxycotinine of a bar on hovering. The legend can also be used to only view either Cotinine or Hydroxycotine levels by clicking either Cotinine/Hydroxycotinine on the legend. I also used different colors for different levels for ease of visualisation.

In [72]:
TOOLTIPS5 = [
    ("Average", "@Avg")
]

p5 = figure(x_range=races,y_range=(0,150),title="Race vs. Cotinine & Hydroxycotinine levels of smokers",height=500,width=550,tooltips=TOOLTIPS5,background_fill_color="#FEFEF8")
p5.vbar(x='Race',top='Avg',source=group_smokers_cot.replace({'Race': race_labels}),legend_label='Cotinine',width=0.6,color=Spectral6[3],alpha=0.4)
p5.vbar(x='Race',top='Avg',source=group_smokers_hydro.replace({'Race': race_labels}),legend_label='Hydroxycotinine',width=0.6,color=Spectral6[4],alpha=0.4)
p5.xaxis.axis_label = "Race"
p5.yaxis.axis_label = "Levels in ng/mL"
p5.legend.click_policy = "hide" 
p5.xaxis.major_label_orientation = 0.8 



p6 = figure(x_range=races,y_range=(0,0.02),title="Race vs. Cotinine & Hydroxycotinine levels of non smokers",height=500,width=550,tooltips=TOOLTIPS5,background_fill_color="#FEFEF8")

p6.vbar(x='Race',top='Avg',source=group_non_smokers_cot.replace({'Race': race_labels}),legend_label='Cotinine',width=0.6,color=Spectral6[3],alpha=0.4)
p6.vbar(x='Race',top='Avg',source=group_non_smokers_hydro.replace({'Race': race_labels}),legend_label='Hydroxycotinine',width=0.6,color=Spectral6[4],alpha=0.4)

p6.xaxis.axis_label = "Race"
p6.yaxis.axis_label = "Levels in ng/mL"
p6.legend.click_policy = "hide" 
p6.xaxis.major_label_orientation = 0.8 


show(row(p5,p6))

<b>Findings:</b> </br>
- The average levels of both Cotinine and Hydroxycotinine of smokers across all races are significantly higher than non-smokers.
- Across all races, smokers have higher levels of Cotinine than Hydroxycotinine whereas non-smokers have same levels of Cotinine and Hydroxycotinine.
- Non-smokers have Cotinine and Hydroxycotinine levels at 0.011 for all races. </br>

For smokers:
- Non-Hispanic White people have highest levels of Cotinine(106.058) and Hydroxicotinine(47.923) which indicates that Non-Hispanic White people are more likely to smoke or be exposed to secondhand smoke than other racial groups.
- Other Race-Including Multi-Racial and Non-Hispanic Black follow next with higher levels of Cotinine(101.56,93.215) and Hydroxycotinine(41.030,33.897)
- Other Hispanic and Mexican American have similar levels of Cotinine(46.407,37.748) and Hydroxycotinine(16.947,13.276).

<b>Exploring anomalous smokers and non-smokers by their response to smoking atleast 100 cigarettes in their lifetime</b>

I grouped the non_smokers dataset using 'Race' column and selected the '100_cig'(Smoked at least 100 cigarettes in life) column and aggregated it using size() and stored the resulting dataframe in non_smokers_anomalous. I called it anomalous because non_smokers should all have '100_cig' column responded with 'No'.

Next, I filtered the smokers dataset by selecting rows where 'Cotinine' levels were below 0.015(not an active smoker) and then grouped it by 'Race' followed by '100_cig' and aggregated it using size() and stored the resulting dataframe in smokers_anomalous. I called it anomalous because smokers should not have 'Cotinine' levels below 0.015. I also filtered the index numbers of smokers who have 'Cotinine' levels below 0.015.

In [73]:
non_smokers_anomalous=non_smokers.groupby(['Race','100_cig']).size().reset_index(name='count')
non_smokers_anomalous=non_smokers_anomalous.groupby(['Race','100_cig'])

smokers_anomalous=smokers.loc[smokers['Cotinine']<0.015].groupby(['Race','100_cig']).size().reset_index(name='count')
smokers_anomalous=smokers_anomalous.groupby(['Race','100_cig'])
smokers_anomalous_index=smokers.where(smokers['Cotinine']<0.015).dropna().index

I used bokeh's nested bar plot to plot the grouped datasets non_smokers_anomalous and smokers_anomalous in different interractive tabs which can be switched on click. I used tooltips which allow to display the count/frequency of a bar on hovering. I also used different colors for different races for ease of visualisation. In a third tab, I also plotted the Hydroxycotinine levels of only those smokers who have 'Cotinine' levels below 0.015 in a line plot using circles to identify data points. I also used hspan to display a green line of 0.015 which is the threshold of Hydroxycotinine level. I used tooltips which allow to display the 'Race' and if they '100_cig' values when hovered over the line.

In [74]:
TOOLTIPS6 = [
    ("Frequency", "@count_mean"),
    ("Race, Smoked 100 cigarettes", "@Race_100_cig")]

TOOLTIPS7 = [
    ("Race", "@Race"),
    ("Smoked 100 cigarettes", "@100_cig")]
    
index_cmap1 = factor_cmap('Race_100_cig', palette=Spectral6, factors=sorted(x['Race'].unique()), end=1)
index_cmap2 = factor_cmap('Race_100_cig', palette=Spectral6, factors=sorted(x['Race'].unique()), end=1)


p7 = figure(title="Non Smokers - Frequency by Race and 100 cigarettes smoked count", height=500, width=800, x_range=non_smokers_anomalous, tooltips=TOOLTIPS6,background_fill_color="#FEFEF8")
p7.vbar(x='Race_100_cig', top='count_mean', width=1, source=non_smokers_anomalous, line_color="white",fill_color=index_cmap1)
p7.x_range.range_padding =0.05
p7.xaxis.axis_label = "100 cigarettes smoked count grouped by Race"
p7.yaxis.axis_label = "Frequency"
p7.xaxis.major_label_orientation = 1.2

p8 = figure(title="Smokers - Frequency by Race and 100 cigarettes smoked count", height=500, width=800, x_range=smokers_anomalous, tooltips=TOOLTIPS6,background_fill_color="#FEFEF8")
p8.vbar(x='Race_100_cig', top='count_mean', width=1, source=smokers_anomalous, line_color="white",fill_color=index_cmap2)
p8.x_range.range_padding = 0.05
p8.xaxis.axis_label = "100 cigarettes smoked count grouped by Race"
p8.yaxis.axis_label = "Frequency"
p8.xaxis.major_label_orientation = 1.2

p9 = figure(title="Smokers - Hydroxycotinin levels", height=500, width=800,background_fill_color="#FEFEF8")
p9.line(x='index',y='Hydroxycotinine', source=smokers.iloc[smokers_anomalous_index,],line_color='#FFB347',line_width=2)
circle=p9.circle(x='index',y='Hydroxycotinine', source=smokers.iloc[smokers_anomalous_index,],size=5)
p9.yaxis.axis_label = "Hydroxycotinine in ng/mL"
p9.hspan(y=0.015, line_width=2, line_color="#8BD688")

hover_circle = HoverTool(renderers=[circle], tooltips=TOOLTIPS7)
p9.add_tools(hover_circle)

tab1 = TabPanel(child=p7, title="Anomalous non smokers") 
tab2 = TabPanel(child=p8, title="Anomalous smokers") 
tab3=TabPanel(child=p9, title="Anomalous smokers Hydroxycotinine") 
tabs = Tabs(tabs=[tab1, tab2,tab3])


show(tabs)
# show(column(p7, p8, p9))

<b>Findings:</b> </br>
Anomalous non-smokers tab:
- All the racial groups have highest numbers of 'No' compared to 'Yes' when asked if they smoked at least 100 cigarettes in life but all racial groups have a small number of people who said 'Yes' to the question. That means, during testing both their 'Cotinine' and 'Hydroxycotinine' levels were below 0.015. According to NHANES report Cotinine has a half-life of about 15-20 hours, therefore it is most likely that these individuals are occational smokers or former smokers and have quit smoking now. Therefore, even if they have smoked 100 cigarettes in their lifetime, it is not necessarily recent. Therefore, their cotinine levels have gone down.
- Among all racial groups, Non-Hispanic White people have the hightest number of them who smoked at least 100 cigarettes in their lifetime, whereas, Non-Hispanic Asian and Other Race-Including Multi-Racial are among the lowest numbers who have smoked at least 100 cigarettes in their lifetime.
- Mexican American. Non-Hispanic Black and Other Hispanic races have similar numbers of people who smoked at least 100 cigarettes in their lifetime.
  
Anomalous smokers tab:
- Except Other Race- Including Multi-Racial, all racial groups have small number of people who responded 'No' when asked if they smoked at least 100 cigarettes in lifetime but their 'Cotinine' and/or 'Hydroxycotinine' levels were above 0.015. This may suggest that they are light/occasional smokers, have started smoking recently or are passive smokers.
- Among all racial groups, Non-Hispanic White people have the hightest number of them who did not smoke at least 100 cigarettes in their lifetime.
- All the other races: Mexican American, Non-Hispanic Asian, Non-Hispanic Black, Other Hispaninc have only 1 person who said 'No' and from these races, Non-Hispaninc Asian, Other Hispanic and Other Race-Including Multi-Racial have no 'Yes' responders. This also shows that the dataset is minimal and might not represent all answers.
  
Anomalous smokers Hydroxycotinine tab:
- All these people have 'Cotinine' levels below 0.015 however, it can be seen that their 'Hydroxycotinine' levels are at or above the green line(threshold of 0.015). This might be due to passive smoking where cotinine levels have declined but hydroxycotinine levels are still elevated.
- Hovering over the line shows that some of these people also did not smoke atleast 100 cigarettes in their lifetime which further suggests that these people might be passive smokers
- Hovering over the line shows that some of these people also did smoke atleast 100 cigarettes in their lifetime which suggests that their cotinine levels most like declined due to high metabolism.

<b>Comparing the cotinine and hydroxycotinine levels of non-smokers and passive smokers</b>

I made passive smokers dataset by filtering the smokers dataset by selecting only rows which have either high 'Cotinine' levels or high 'Hydroxycotinine' levels. I further used multiple conditions by selecting only those rows where respondants answered 'No' when asked if they smoked atleast 100 cigarettes in their life and have either been at Job, Home, Bar, Car or Other places and someone else smoked indoors/used e-cigs in all those places while they were there in the last 7 days. 

In [75]:
passive_smokers=smokers.loc[
(((smokers['Cotinine']<0.015) & (smokers['Hydroxycotinine']>=0.015)) | ((smokers['Cotinine']>=0.015) & (smokers['Hydroxycotinine']<0.015))) & 
(smokers['100_cig'] == 'No') & 
(
    ((smokers['Job'] == 1) & (smokers['Job_indoors'] == 1)) |
    ((smokers['Home'] == 1) & (smokers['Home_indoors'] == 1)) |
    ((smokers['Bar'] == 1) & (smokers['Bar_indoors'] == 1)) |
    ((smokers['Car'] == 1) & (smokers['Car_indoors'] == 1)) |
    ((smokers['Other'] == 1) & (smokers['Other_indoors'] == 1)) |
    (smokers['E_cigs'] == 1)
)]

I grouped the passive smokers dataset using 'Race' column and selected the 'Cotinine' and 'Hydroxycotinine' column and aggregated them using mean and stored the resulting dataframe in group_passive_smokers. 

In [76]:
group_passive_smokers=passive_smokers.groupby(['Race'])[['Cotinine','Hydroxycotinine']].mean().reset_index()
group_passive_smokers

Race  Cotinine  Hydroxycotinine
0                     Mexican American  0.029894         0.011000
1                   Non-Hispanic Asian  0.108238         0.015429
2                   Non-Hispanic Black  0.051219         0.011000
3                   Non-Hispanic White  0.028656         0.011279
4                       Other Hispanic  0.023870         0.011000
5  Other Race - Including Multi-Racial  0.044941         0.011000

I used bokeh's bar plot to plot the grouped datasets group_passive_smokers and group_non_smokers_cot on top of one another using alpha=0.4 to reduce the opacity to vosualize the Cotinine levels. I did the same to again plot the grouped datasets group_passive_smokers and group_non_smokers_hydro on top of one another using alpha=0.4 to reduce the opacity to vosualize the Hydroxycotinine levels. I used tooltips which allow to display the average levels of Cotinie and Hydroxycotinine of a bar on hovering. The legend can also be used to only view either Non Smokers or Passive Smokers type by clicking either Non Smokers/Passive Smokers on the legend. I also used different colors for different types for ease of visualisation. I also used hspan to display a green line of 0.015 which is the threshold of Cotinine and Hydroxycotinine levels.

In [77]:
TOOLTIPS8 = [
    ("Average", "@Cotinine")
]

TOOLTIPS9 = [
    ("Average", "@Hydroxycotinine")
]

TOOLTIPS10 = [
    ("Average", "@Avg")
]

p10 = figure(x_range=races,title="Race vs. mean Cotinine levels of non smokers and passive smokers",height=500,width=550,tooltips=TOOLTIPS8,background_fill_color="#FEFEF8")

plt1=p10.vbar(x='Race',top='Avg',source=group_non_smokers_cot.replace({'Race': race_labels}),legend_label='Non smokers',width=0.6,color=Spectral6[4],alpha=0.4)
plt2=p10.vbar(x='Race',top='Cotinine',source=group_passive_smokers.replace({'Race': race_labels}),legend_label='Passive smokers',width=0.6,color=Spectral6[3],alpha=0.4)
p10.hspan(y=0.015, line_width=2, line_color="#8BD688")

# p4.vbar(x='Race',top='Hscrp',source=non_smokers.replace({'Race': race_labels}),legend_label='Hscrp',width=0.6,color=Category10[3][2],alpha=0.4)
# customize plot appearance
# # p.y_range.start = 0
p10.xaxis.axis_label = "Race"
p10.yaxis.axis_label = "Cotinine Levels in ng/mL"
p10.legend.click_policy = "hide"  # set the legend click policy to hide
p10.xaxis.major_label_orientation = 0.8  # rotate labels by roughly pi/4



hover_non_smokers_cot = HoverTool(renderers=[plt1], tooltips=TOOLTIPS10)
hover_passive_smokers_cot = HoverTool(renderers=[plt2], tooltips=TOOLTIPS8)

# Add the hover tools to the figure
p10.add_tools(hover_non_smokers_cot, hover_passive_smokers_cot)


p11 = figure(
    x_range=races,
    # y_range=(0,0.02),
    title="Race vs. mean Hydroxicotinine levels of non smokers and passive smokers",
    height=500,
    width=550,
    #sizing_mode="stretch_width",  # use the full width of the parent element
    tooltips=TOOLTIPS9,background_fill_color="#FEFEF8"
    # output_backend="webgl",  # use webgl to speed up rendering (https://docs.bokeh.org/en/latest/docs/user_guide/output/webgl.html)
    # active_drag="box_zoom",  # enable box zoom by default
)

plt3=p11.vbar(x='Race',top='Avg',source=group_non_smokers_hydro.replace({'Race': race_labels}),legend_label='Non smokers',width=0.6,color=Spectral6[4],alpha=0.4)
plt4=p11.vbar(x='Race',top='Hydroxycotinine',source=group_passive_smokers.replace({'Race': race_labels}),legend_label='Passive smokers',width=0.6,color=Spectral6[3],alpha=0.4)
p11.hspan(y=0.015, line_width=2, line_color="#8BD688")

# p4.vbar(x='Race',top='Hscrp',source=non_smokers.replace({'Race': race_labels}),legend_label='Hscrp',width=0.6,color=Category10[3][2],alpha=0.4)
# customize plot appearance
# # p.y_range.start = 0
p11.xaxis.axis_label = "Race"
p11.yaxis.axis_label = "Hydroxicotinine Levels in ng/mL"
p11.legend.click_policy = "hide"  # set the legend click policy to hide
p11.xaxis.major_label_orientation = 0.8  # rotate labels by roughly pi/4

hover_non_smokers_hydro = HoverTool(renderers=[plt3], tooltips=TOOLTIPS10)
hover_passive_smokers_hydro = HoverTool(renderers=[plt4], tooltips=TOOLTIPS9)

# Add the hover tools to the figure
p11.add_tools(hover_non_smokers_hydro, hover_passive_smokers_hydro)


show(row(p10,p11))

<b>Findings:</b> </br>

Cotinine Levels:
- For passive smokers the levels of Cotinine levels are above the threshold of 0.015 across all races. This means that they were recently exposed to high level of passive smoking.
- For passive smokers, among all races, the highest average Cotinine level(0.108) can be detected in Non-Hispanic Asian people which means they likely have the highest exposure to passive smoke among the racial groups.
- The second and third highest are Non-Hispanic Black and Other Race-Including Multi-Racial with 0.05122 and 0.04494.
- The Mexical American, Non-Hispanic White and Other Hispanic have close average values(0.02989,0.02866,0.02387) and are towards the lower end.

Hydroxycotinine Levels:
- For passive smokers the levels of Hydroxycotinine levels are above the threshold of 0.015 only for Non-Hispanic Asians. This means there was a long time exposure to passive smoking in this case.


#### Reflection on NHANES data privacy rules

During NHANES surveys, the participants' names remain disconnected from their questionnaire responses and test outcomes. All information that could potentially identify individuals or their families, such as names, addresses, phone numbers, and workplaces, is eliminated. Additionally, data concerning very specific geographical areas, which could potentially lead to the identification of individuals, are not disclosed. Each participant receives a distinct identification number solely for the survey. Participation is voluntary, and all responses are kept confidential. Besides that, NHANES databases are safeguarded by passwords and encryption, accessible only to authorized personnel. NCHS integrates participants' protected data with data from numerous other survey participants. The combined data are carefully checked to prevent any linkage to individual participants, families, or persons.

NHANES places a high emphasis on data privacy and ethics and therefore, I made sure that my analysis is conducted with integrity and respects the rights and confidentiality of participants.

